groups:
  - name: job_portal_rules
    rules:
      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, rate(http_request_latency_seconds_bucket[5m])) > 0.2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Temps de réponse élevé"
          description: "95% des requêtes prennent plus de 200ms."

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status_code=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.01
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Taux d'erreur élevé"
          description: "Le taux d'erreur dépasse 1% sur 5 minutes."
